name: make_docs
on:
  push:
    branches:
      - master  # so, the worflow runs whenever main changes.
jobs:
  make_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - run: pip install -r docs/requirements.txt
      - run: mkdocs gh-deploy --force --clean --verbose
