# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Tilly (staging)

on:
  pull_request:
    types:
      - opened
      - synchronize # when new commits are pushed to the PR
  workflow_dispatch:

env:
  ENVIRONMENT_NAME: staging
  APP_NAME: app-govtech
  AZ_IMAGE_TAG: acrgovtech.azurecr.io/acrgovtech/staging:${{ github.sha }}
  AZ_CONTAINER_REGISTRY: acrgovtech.azurecr.io/
  AZ_CONTAINER_REGISTRY_USERNAME: ${{ secrets.AzureAppService_ContainerUsername_c23081512421436eb33a64d99930cbf9 }}
  AZ_CONTAINER_REGISTRY_PASSWORD: ${{ secrets.AzureAppService_ContainerPassword_fd715ae5e09d4867b962e7b29e048594 }}
  AZ_PUBLISH_PROFILE: ${{ secrets.AZ_PUBLISH_PROFILE }}
#  LOGIN_NAME: ${{ secrets.LOGIN_NAME }}
#  LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}

jobs:

  metadata:
    runs-on: ubuntu-latest
    outputs:
      git_metadata: ${{ steps.git_metadata.outputs.git_metadata }}

    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: .

    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${{ github.sha }} | cut -c1-8`" >> $GITHUB_ENV

    - name: Get the last commit date
      run: echo "COMMIT_DATE=`git log -1 --format=%cd --date=format:'%b %d, %H:%M' HEAD`" >> $GITHUB_ENV

    - name: Get the last commit date
      id: git_metadata
      run: echo "git_metadata=${{ env.SHORT_SHA }}-${{ github.event.pusher.name  }}-${{ env.COMMIT_DATE }}" >> "$GITHUB_OUTPUT"

  build:
    runs-on: ubuntu-latest
    needs: metadata

    steps:
    - uses: actions/checkout@v4

    - name: Debugging - List ai directory contents
      run: ls -al ./ai

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.AZ_CONTAINER_REGISTRY }}
        username: ${{ env.AZ_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ env.AZ_CONTAINER_REGISTRY_PASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ env.AZ_IMAGE_TAG }}
        file: ./ai/Dockerfile
        build-args: |
            GIT_METADATA=${{ needs.metadata.outputs.git_metadata }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: staging
    outputs:
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App testing
      uses: azure/webapps-deploy@v2
      id: deploy-to-webapp
      with:
        app-name: ${{ env.APP_NAME }}
        slot-name: ${{ env.ENVIRONMENT_NAME }}
        publish-profile: ${{ env.AZ_PUBLISH_PROFILE }}
        images:  ${{ env.AZ_IMAGE_TAG }}

  ping:
    runs-on: ubuntu-latest
    needs: [deploy, metadata]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        sparse-checkout: .github

    - name: Ping Endpoint
      uses: shahnozaAI/ping-url@v1.0.8
      with:
        url: ${{ needs.deploy.outputs.url }}/heartbeat/
        response_field: 'version'
        response_value: ${{ needs.metadata.outputs.git_metadata }}
        interval: '30'
        timeout: '900'